package ErrorHandler;

public enum VrstaGreske {
    ISPRAVNOPRAVILO,NEMAQUERY,SYNTAXERROR,PRAZANSELECT,GROUPBY,GROUPBYBEZSVIHPARAMETARA,HAVINGPARAMETRI,AndOrdHavingBezHaving,INIT,ORANDWHERE,WHEREBETWEEN,WHEREIN,WHEREPARAMETRI,JOINON
}
